name: Docker CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - src/**
  pull_request:
    branches: [ main ]
    paths:
      - src/**

jobs:
  build:
    name: build and push Docker image
    runs-on: ubuntu-latest
    steps: 
      # 1 
      - uses: actions/checkout@v4
      # 2  
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 3   
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/galeria:latest



aws:
    name: Deploy image to aws
    needs: build # Solo corre si build sale bien
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # 1. Copia el archivo docker-compose.yml al servidor
    - name: copy docker compose via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_HOSTNAME }}
        username: ${{ secrets.AWS_USERNAME }}
        port: 22
        key: ${{ secrets.AWS_PRIVATEKEY }}
        source: "docker-compose.yml"
        target: /home/${{ secrets.AWS_USERNAME }} # Ajustado según el usuario

    # 2. Ejecuta los comandos en el servidor remoto
    - name: script deploy docker services
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOSTNAME }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_PRIVATEKEY }}
        port: 22
        script: |
            sleep 60
            docker compose down --rmi all
            docker compose up -d